# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20160818_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set([('product', 'category')]),
        ),
    ]
